### ISSUE TITLE
Add GPS sensor

### ISSUE THREAD

**Issue by bsb808** [Field-Robotics-Lab/glider_hybrid_whoi#1]
* Add Hector GPS plugin to hybrid and non-hybrid underwater glider models: http://wiki.ros.org/hector_gazebo_plugins
* Tune the GPS configuration parameters to reflect the glider GPS sensor performance supplied by WHOI
* The GPS only gets a fix when at the surface (antenna out of the water).
    * Can we simulate this behavior with the existing plugin?  
    * If not - add an intermediate ROS node in Python that subscribes the the plugin outputs and only published the GPS fix information when glider is at this surface.  Can use the model state information from Gazebo to determine if the glider is at the surface (or some other method).
   * Could also evaluate if the UUV Simulator plugin would be of use https://github.com/uuvsimulator/uuv_simulator/blob/master/uuv_sensor_plugins/uuv_sensor_ros_plugins/include/uuv_sensor_ros_plugins/GPSROSPlugin.hh

See the [uw_glider_itnerface.graphml](https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/blob/master/uw_glider_interface.graphml)

**Comment by bsb808** [comment]
@WHOI Please provide the performance parameters for the GPS receiver onboard the gliders.  Best if you can specify the "XML Parameters" listed as part of the Hector ROS GPS Plugin: http://wiki.ros.org/hector_gazebo_plugins#GazeboRosGps

**Comment by BruceMty** [comment]
@bsb808 I did not find GPS configuration parameters supplied by WHOI.  I used values found at https://answers.gazebosim.org//question/6220/gps-sensor-in-gazebo-19/a.  For elevation, I enable GPS publish when elevation reaches -0.1 meters.

**Comment by bsb808** [comment]
@whoi Please provide the performance parameters for the GPS receiver onboard the gliders. Best if you can specify the "XML Parameters" listed as part of the Hector ROS GPS Plugin: http://wiki.ros.org/hector_gazebo_plugins#GazeboRosGps

**Comment by greg-burgess** [comment]
Performance Parameters for GPS onboard Slocum Glider
--most interested in starting point (before submerging), and ending point (surfacing) for each dive. Also, the minute prior to submerging in order to calculate the surface drift of the glider. 

**updateRate: 4000 (milliseconds)** 

robotNamespace: (unsure -use standard prefixes)
bodyName: glider?
frameId: defaults to empty
topicName: default
velocityTopicName: default

**referenceLatitude: double degrees north**
**referenceLongitude: double degrees east**

referenceHeading: not needed
referenceAltitude: not needed

status: default is fine
service: default is fine
offset: negligible and within noise (0,0,0)

*most likely will not need this information, default or zero is fine
drift: use default
driftFrequency: use default
gaussianNoise: use default
velocityOffset: default
velocityDrift: default
velocityDriftFrequency: default
velocityGaussianNoise: default

**Comment by woensug-choi** [comment]
Made a PR https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/pull/28 which add a hector IMU sensor.
I've set the update rate to 0.25 Hz. Performance parameters are not configured yet (set to zero)

**Comment by woensug-choi** [comment]
PR https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/pull/28 is merged.

Parameters
```
<updateRate>0.25</updateRate>
<drift>0.0 0.0 0.0</drift>
<gaussianNoise>0.0 0.0 0.0</gaussianNoise>
<velocityDrift>0 0 0</velocityDrift>
<velocityGaussianNoise>0.0 0.0 0.0</velocityGaussianNoise>
<epsg_projection>26987</epsg_projection>
```

Topics
```
/glider_hybrid_whoi/hector_gps
/glider_hybrid_whoi/hector_gps/position/parameter_descriptions
/glider_hybrid_whoi/hector_gps/position/parameter_updates
/glider_hybrid_whoi/hector_gps/status/parameter_descriptions
/glider_hybrid_whoi/hector_gps/status/parameter_updates
/glider_hybrid_whoi/hector_gps/velocity/parameter_descriptions
/glider_hybrid_whoi/hector_gps/velocity/parameter_updates
/glider_hybrid_whoi/hector_gps_velocity
```

Closing this issue page as it was for initial sensor set-up discussions. Please revive this issue page when we need further specifications or discussions.
